### ISSUE TITLE
Fix duplicate number

### ISSUE THREAD

**Issue by inghylt** [NBISweden/predictprotein-webserver-topcons2#41]
https://topcons.net/pred/help/

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/70ca2e67-75a7-4d65-b320-8a80bb9ae58b)

Replace 4. 4. 5. with 4. 5. 6.

**Comment by nanjiangshu** [comment]
Thanks a lot @inghylt for pointing out this bug, good catch. I have created a PR https://github.com/NBISweden/predictprotein-webserver-topcons2/pull/42 to solve this bug. 

For this project. I will merge it myself.

**Comment by inghylt** [comment]
Nice! It was actually @e0 who spotted the issue when we talked about work previously today so all cred goes to him :)
